redwood: Import libqti-perfd-client namespace
This fixes the following error:

error: vendor/xiaomi/redwood/Android.bp:7949:1: "libgf_hal" depends on undefined module "libqti-perfd-client".
Module "libgf_hal" is defined in namespace "vendor/xiaomi/redwood" which can read these 6 namespaces: ["vendor/xiaomi/redwood" "hardware/qcom-caf/sm8350" "hardware/
xiaomi" "vendor/qcom/opensource/display" "vendor/xiaomi/sm8350-common" "."]
Module "libqti-perfd-client" can be found in these namespaces: ["hardware/qcom-caf/common/libqti-perfd-client"]
Or did you mean ["clientinterface_test" "fmtlib-test-defaults" "init.qti.usb.qmaa.rc" "libbinderdebug_test" "libfilterfw_native" "libperfetto_hprofd" "libperfettoct
s_jni" "libperfmgr_defaults" "libperftestscore_jni" "qti-telephony-utils" "qti_powerhal_headers" "wifi-service-common"]?

Signed-off-by: Tashfin Shakeer Rhythm <tashfinshakeerrhythm@gmail.com>